name: Documentation Generation
on: 
  workflow_dispatch:
  pull_request:
    branches: [main, dev]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
          wget https://doxygen.nl/files/doxygen-1.14.0.linux.bin.tar.gz
          tar -xzf doxygen-1.14.0.linux.bin.tar.gz
          sudo cp doxygen-1.14.0/bin/doxygen /usr/local/bin/
    - name: Generate internal docs
      run: |
        mkdir -p build/docs/internal
        doxygen docs/internal/Doxyfile_internal
    - name: Generate public docs
      run: |
        mkdir -p build/docs/public
        doxygen docs/public/Doxyfile_public

    - name: Upload internal Docs
      uses: actions/upload-artifact@v4
      with:
        name: docs-internal
        path: build/docs/internal/html/
    - name: Upload public Docs
      uses: actions/upload-artifact@v4
      with:
        name: docs-public
        path: build/docs/public/html/

    - name: Upload undocumented items
      uses: actions/upload-artifact@v4
      with:
        name: undocumented-report
        path: build/undoc.log

# TODO: Upload to github pages
