name: Documentation Generation
on: 
  workflow_dispatch:
  pull_request:
    branches: [main, dev]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
          wget https://doxygen.nl/files/doxygen-1.14.0.linux.bin.tar.gz
          tar -xzf doxygen-1.14.0.linux.bin.tar.gz
          sudo cp doxygen-1.14.0/bin/doxygen /usr/local/bin/
    - name: Generate internal docs
      run: |
        mkdir build/docs/internal
        doxygen docs/internal/Doxyfile_internal || true
    - name: Upload undoc.log artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: undoc-log
        path: build/docs/internal/undoc.log

    - name: Generate public docs
      run: |
        mkdir build/docs/public
        doxygen docs/public/Doxyfile_public || true

    - name: Upload Docs
      uses: actions/upload-artifact@v4
      with:
        name: docs-internal
        path: build/docs/internal/html
    - name: Upload public Docs
      uses: actions/upload-artifact@v4
      with:
        name: docs-public
        path: build/docs/public/html

    - name: Get undocumented items
      run: |
          mkdir -p build/undoc_report
          grep -i "function" undoc.log    || true > build/undoc_report/functions.txt
          grep -i "namespace" undoc.log   || true > build/undoc_report/namespaces.txt
          grep -i "file" undoc.log        || true > build/undoc_report/files.txt
          grep -i "class" undoc.log       || true > build/undoc_report/classes.txt
          grep -i "struct" undoc.log      || true > build/undoc_report/structs.txt
          grep -i "enum" undoc.log        || true > build/undoc_report/enums.txt

    - name: Upload undocumented items
      uses: actions/upload-artifact@v4
      with:
        name: undocumented-report
        path: build/docs/internal/html/

# TODO: Upload to github pages
